name: Check Pull Request
on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
  merge_group:

jobs:
  check-title:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - name: Check title
        run: |
          title="${{ github.event.pull_request.title }}"
          title_escaped=${title//\'/\'}
          if [ "$title" == "feat: update generated APIs" ]; then
            echo "Invalid title."
            exit 1
          else
            echo "$title_escaped" | bun commitlint
          fi
