name: Deploy to NPM

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * MON"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3.6.0
        with:
          fetch-depth: "0"
          persist-credentials: false
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Git Identity
        run: |
          git config --global user.name 'scaleway-bot'
          git config --global user.email 'github@scaleway.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build
      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: bun lerna publish -y --create-release github
        env:
          HUSKY: 0
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
