name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  typecheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build
      - run: bun tsc --noEmit

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build
      - run: bun run lint

  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        test-environment:
          - node
          - jsdom
    steps:
      - uses: actions/checkout@v4
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build
      - run: bun run test:coverage --testEnvironment ${{ matrix.test-environment }}
      - uses: codecov/codecov-action@v3.1.4
